# Oracle JDK8 is only supported on trusty (instead of the default, xenial)
dist: trusty
language: java
jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
